version: '3.8'

services:
  php:
    build: .
    container_name: php_api
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always  

  nginx:
    image: nginx:latest
    container_name: nginx_api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: mysql_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: greengarden
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./greengarden.sql:/docker-entrypoint-initdb.d/greengarden.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_api
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: always
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api/swagger.yaml
    volumes:
      - ./swagger.yaml:/api/swagger.yaml

  images:
    image: nginx
    container_name: images_server
    restart: always
    volumes:
      - ./images:/usr/share/nginx/html/images
    ports:
      - "8084:80"

volumes:
  db_data:
